### PR TITLE
Feat : Support go module import

### PR DESCRIPTION
**Pull request by luckoseabraham**
Allows go module support https://github.com/env0/terratag/issues/117

### CODE REVIEW

**Review by TomerHeber — COMMENTED** [review]
@luckoseabraham - what are your thoughts on renaming "cli" directory to "terratag".
I'm thinking as a future ticket to move everything else to "internal".

Let me know what you think. Thanks!

**Comment by luckoseabraham** [comment]
> @luckoseabraham - what are your thoughts on renaming "cli" directory to "terratag". I'm thinking as a future ticket to move everything else to "internal".
> 
> Let me know what you think. Thanks!

Hey @TomerHeber  - Thanks for the comment.
I did briefly consider the option. The only thing that stopped me is that the resulting package name would have a redundant `terratag`. Something like `github.com/env0/terratag/terratag`. 
That being said, if this is something the maintainers are okay with, I will be glad to make the change.

**Comment by luckoseabraham** [comment]
> @luckoseabraham - what are your thoughts on renaming "cli" directory to "terratag". I'm thinking as a future ticket to move everything else to "internal".
> 
> Let me know what you think. Thanks!

I think the move to internal is a good idea especially here since there is not really a use case **yet** where internals needs be used alone. The structure would become a bit complicated tho.
We would have something like this.

```
terratag/
├── go.mod
├── go.sum
├── main.go
└── terratag
    ├── internal
    │   ├── providers
    │   ├── tag_keys
    │   └── terraform
    └── terratag.go
```

Another thing I would ask to consider would be about the strategy for folks trying to use one of the child packages in a stand-alone manner and would start getting requests to expose some packages (something like this : https://github.com/open-policy-agent/conftest/issues/209 )

**Comment by TomerHeber** [comment]
> > @luckoseabraham - what are your thoughts on renaming "cli" directory to "terratag". I'm thinking as a future ticket to move everything else to "internal".
> > Let me know what you think. Thanks!
> 
> I think the move to internal is a good idea especially here since there is not really a use case **yet** where internals needs be used alone. The structure would become a bit complicated tho. We would have something like this.
> 
> ```
> terratag/
> ├── go.mod
> ├── go.sum
> ├── main.go
> └── terratag
>     ├── internal
>     │   ├── providers
>     │   ├── tag_keys
>     │   └── terraform
>     └── terratag.go
> ```
> 
> Another thing I would ask to consider would be about the strategy for folks trying to use one of the child packages in a stand-alone manner and would start getting requests to expose some packages (something like this : [open-policy-agent/conftest#209](https://github.com/open-policy-agent/conftest/issues/209) )

Understood

> > @luckoseabraham - what are your thoughts on renaming "cli" directory to "terratag". I'm thinking as a future ticket to move everything else to "internal".
> > Let me know what you think. Thanks!
> 
> Hey @TomerHeber - Thanks for the comment. I did briefly consider the option. The only thing that stopped me is that the resulting package name would have a redundant `terratag`. Something like `github.com/env0/terratag/terratag`. That being said, if this is something the maintainers are okay with, I will be glad to make the change.

@luckoseabraham - thank you for all the details.
There is a way to resolve this redundancy. However, it's out of scope for this PR.
One last question: what functionality (functions) are you looking to expose as a library?

**Comment by luckoseabraham** [comment]
> @luckoseabraham - thank you for all the details. There is a way to resolve this redundancy. However, it's out of scope for this PR. One last question: what functionality (functions) are you looking to expose as a library?

Mainly the Terratag function for initializing. https://github.com/env0/terratag/blob/v0.1.37/main.go#L51 
Today I have to copy the entire initialization logic in main.go into a separate file. The reason I dont want to do this is to avoid trying to copy the code from any changes that comes in.

Also just to confirm, Would you like the cli package renamed to terratag ?

**Comment by TomerHeber** [comment]
> > @luckoseabraham - thank you for all the details. There is a way to resolve this redundancy. However, it's out of scope for this PR. One last question: what functionality (functions) are you looking to expose as a library?
> 
> Mainly the Terratag function for initializing. https://github.com/env0/terratag/blob/v0.1.37/main.go#L51 Today I have to copy the entire initialization logic in main.go into a separate file. The reason I dont want to do this is to avoid trying to copy the code from any changes that comes in.
> 
> Also just to confirm, Would you like the cli package renamed to terratag ?

@luckoseabraham thank you for the details.
No need to rename at this time. Thanks!

**Review by TomerHeber — APPROVED** [review]
LGTM.

**Comment by luckoseabraham** [comment]
Hey @TomerHeber  - The LGTM comment doesnt seem to trigger the merge. Could you please merge ?

**Pull request merged**
