### PR TITLE
Feat: add support for azapi

### PR DESCRIPTION
**Pull request by TomerHeber**
Added support azapi provider.
Added a new test.

### CODE REVIEW

**Review by eranelbaz — COMMENTED** [review]
Can you add a test for `azapi` where there are no tags?

**Comment by TomerHeber** [comment]
> Can you add a test for `azapi` where there are no tags?

I updated the tests and added resources with no tags. 
It works like the rest of the providers. I'm unsure there's any benefit in adding anything else, but let me know...

**Review by eranelbaz — APPROVED** [review]

**Comment by eranelbaz** [comment]
I just wanted to be on the safe side since we have two options
- Tags already there and we want to append
- No Tags block and we need to create one

**Comment by TomerHeber** [comment]
> I just wanted to be on the safe side since we have two options
> 
> * Tags already there and we want to append
> * No Tags block and we need to create one

makes sense!
I have added these.

**Pull request merged**
