### PR TITLE
Feat: add --skip to exclude resources

### PR DESCRIPTION
**Pull request by duncan485**
I've been using terratag for a while now and recently encountered the need to have terratag tag every resource **except** a certain resource type. As Go does not support a negative lookahead regex, I was not able to do this with the existing --filter argument. Therefore I've created this MR that adds an additional --invertFilter bool which basically changes the filter argument from being inclusive to exclusive (i.e. anything that matches the filter regex will **not** be tagged if --invertFilter is set to true)

I've set the default of invertFilter to false to it will not introduce any breaking changes. 

Thanks in advance for any comments and I'm looking forward to hear what you think.

### CODE REVIEW

**Comment by duncan485** [comment]
Hi @TomerHeber any thoughts on this?

**Comment by TomerHeber** [comment]
> Hi @TomerHeber any thoughts on this?

@duncan485 - sorry for the delay. Overall looks good.
I'm waiting for some feedback from the core Env0 team. Will update you when I hear back.

**Comment by TomerHeber** [comment]
Hi @duncan485 

Thank you for your contribution.
I have discussed this with the env0 team. They believe that we should have a `--reject` that receives a regex.
Anything that matches the regex will be excluded.

I wanted to know your thoughts on the matter.

If this change is too large (or not time), please let me know, and I can pick it up.

Thank you,
Tomer.

**Comment by duncan485** [comment]
Hey Tomer, sounds good. I'd be happy to work on that. Will update the PR soon. Thanks for the feedback!

**Comment by duncan485** [comment]
Hey @TomerHeber I thought some more on this and feel like a --skip argument might be more descriptive than --reject. I've updated the PR to implement a skip argument (having the same behaviour as the reject would). 

What do you think?

**Review by TomerHeber — APPROVED** [review]
LGTM!
Thank you for your contribution!

**Pull request merged**
