### PR TITLE
Fix test for a new flag filter.

### PR DESCRIPTION
**Pull request by arybolovlev**
Hello,

I just notice that tests for a new flag `filter` are failing for the following reason:

```
# tfenv use 1.0.0 && go test -v -run ^TestTerraform1o0WithFilter$
...
    terratag_test.go:105:
        test/fixture/terraform_15_1.0_filter/aws_azure/out/main.terratag.tf does not match test/fixture/terraform_15_1.0_filter/aws_azure/expected/main.terratag.tf
...
```

After investigation, I found out that the fix is quite simple and just added an extra empty line to the end of the following file: `test/fixture/terraform_15_1.0_filter/aws_azure/expected/main.terratag.tf`

Now tests are working with no issues.

I also notice that tests for a new flag `filter` are not part of the CI yet. I am not sure if I am allowed to change the GitHub workflow, so I remained it untouched.

Thank you.

### CODE REVIEW

**Comment by yaronya** [comment]
> I also notice that tests for a new flag filter are not part of the CI yet. I am not sure if I am allowed to change the GitHub workflow, so I remained it untouched.

@arybolovlev feel free to add it to the `terraform_version` matrix configuration of the `ci` github action so it could run and we can verify its status as a part of this pull request 🙏

**Comment by yaronya** [comment]
Revisiting the test fixtures change introduced in #94, I was wondering if we can keep the test fixtures to represent the version permutations solely, and not any specific flag use case (i.e - the `filter` flag scenario should reside under the `15_1.0` fixture and not under its designated fixture)
I believe that supporting these specific flags permutations could lead to a too big test fixture list.

@arybolovlev do you think this is something you could contribute within this PR (or another one)? 🙏

**Comment by razbensimon** [comment]
Hey @arybolovlev, it's ok to do so in this PR. 
Thanks for your contribution!

**Comment by yaronya** [comment]
Hey @arybolovlev 
We'd like to release a version soon - would you think this is something you could contribute in the upcoming week or so? 🙏

**Comment by avnerenv0** [comment]
@arybolovlev Thanks for the contribution.

I understand there are some pending items here.
Since this PR is open without activity for 20 days, if you're not gonna follow up on it the PR will be closed in a couple of days.

Thank you 🙏

**Comment by avnerenv0** [comment]
Closing stale

<div><br/>via <a href="https://giphy.com/janetmac/">Janet Mac</a> on <a href="https://giphy.com/gifs/animation-animated-illustration-l9VRGqyVjBDUpvOyFT">GIPHY</a></div>

**Pull request closed without merging**
